### ISSUE TITLE
order in "full consultation order" not reflected in the JSON representation of the version (PH-#2935)

### ISSUE THREAD

**Issue by alanvonlanthen** [Wavemind/liwi-backend#105]
Can't find "Sunken eyes" or "Skin pinch" in the full_order_json node of https://medalcreator.unisante.ch/api/v1/versions/58 despite their being present in https://medalcreator.unisante.ch/algorithms/1/versions/58/full_order (resulting in these questions apprearing under "additional follow-up questions" at the PE step of the consultation stage

**Comment by ManuBarchich** [comment]
J'ai check sur prod, le noeud est bien présent dans le json et dans le champ, bug toujours d'actualité ?

**Comment by alanvonlanthen** [comment]
je n'arrive plus à reproduire non plus, ni en test (TIM KE, SN) ni en prod (DYN TZ 2.1) => on ferme
![Screenshot_20220218-165133_medAL-reader](https://user-images.githubusercontent.com/2785940/154716825-c6e8ef1e-3aa8-41c4-a03b-c08351172ac8.jpg)
)
