### ISSUE TITLE
Activating the YI flag in a variable does not make it pink in the "Full consultation order view" (PH-#2910) 

### ISSUE THREAD

**Issue by alanvonlanthen** [Wavemind/liwi-backend#106]
environment: medALcreator.unisante.ch
to reproduce: in any algorithm, flag any orderable variable as YI, go check to the full consultation order for a version of this algorithm. => the variable doesn't appear in pink

**Comment by ManuBarchich** [comment]
J'ai modifié un noeud pour le mettre en neonat. Celui-ci est bien devenu rose dans le full order.

**Comment by alanvonlanthen** [comment]
can't reproduce in test anymore. Probably fixed by another story. Closing this one :)
