### ISSUE TITLE
Missing translations in the interface when default language !=EN (PH-#2959) / (PH-#3217) / (PH-#3209)

### ISSUE THREAD

**Issue by alanvonlanthen** [Wavemind/liwi-backend#107]
1. List of impacted diagrams still in English. If no English translation available (as for PS-97 in this example), no label displayed at all: 
![image](https://user-images.githubusercontent.com/2785940/152125376-09bdf84b-8097-4589-a7fe-8879aedd3292.png)

2. Detail page for DF, for example: DF name in the title must be in the default language
![image](https://user-images.githubusercontent.com/2785940/152125773-e253214f-143e-49bd-a947-8c615169406d.png)

Globally, all labels and descriptions must be displayed in default language

**Comment by ManuBarchich** [comment]
Egalement les interfaces d'exclusion

**Comment by alanvonlanthen** [comment]
@ManuBarchich pas tout à fait fini. Désolé... Il reste ce scénario à hotfixer: listes déroulantes dans les exclusions de DF. Le label du DF est toujours en anglais:
![image](https://user-images.githubusercontent.com/2785940/153246209-d7f212e9-6bdf-45d8-893c-a3316d9d46ff.png)
