### ISSUE TITLE
Issue with the translation file upload for SN (PH-#3221)

### ISSUE THREAD

**Issue by alanvonlanthen** [Wavemind/liwi-backend#113]
Environment: [medALcreator.unisante.ch](http://medalcreator.unisante.ch/)
 
Issue: file not actually imported (despite success message on green background after import)
 
To reproduce:
1. "Generate tranlations excel" file from https://medalcreator.unisante.ch/algorithms/7/versions/41/translations
2. Open file in EDIT mode, go to the "Question sequences" tab, add Label (en) for id 28699/PS107: "Dripping nose" => save
3. Upload file. Check Success message
4. Hit "generate translations excel" file again, open downloaded file. The translation is not there

**Comment by ManuBarchich** [comment]
L'algo 7 est en français, les modifs sont sauvées en français
