### ISSUE TITLE
Pre-referral duration presentation in medAL-C export (PH-#3220)

### ISSUE THREAD

**Issue by alanvonlanthen** [Wavemind/liwi-backend#114]
1. Drugs in diagnoses tab missing from variable export 
2. When added, add "pre-referral" (or other info) instead of empty duration for pre-referral drugs

(Lisa originally asked to have this in the translation file, because this is where we have the "Drugs in diagnoses" tab currently, but I think we'll all agree that the variable export is where this needs to happen)

**Comment by ManuBarchich** [comment]
Je n'ai rien compris au point 1. Et du coup le 2, tu es sûr ?

**Comment by ManuBarchich** [comment]
1. Il faut retranscrire le tab "Drugs in diagnoses" présent dans l'export de trad dans l'export des variables. 
2. Dans ce dit tab, uniquement pour l'export variables, ajouter l'information d'un pre-referral pour qu'on ne pense pas à tort que la duration n'a pas été saisie

**Comment by alanvonlanthen** [comment]
au top !
