### ISSUE TITLE
Drug and Management cannot be deleted (PH #3239)

### ISSUE THREAD

**Issue by Devstrap** [Wavemind/liwi-backend#117]
## Describe the bug
 I get an error message that something went wrong when I tried to delete a drug or Management

## Context
- Environment: Test
- Full URLs: https://liwi-test.wavelab.top/algorithms/8/drugs/10615 | https://liwi-test.wavelab.top/algorithms/29/managements/24619/
- Use IDs : Algorithms 8 versions 44 | Algorithms 29 versions 57

## To Reproduce
Steps to reproduce the behavior :
1. Try deleting DR14 and M139
2. See errors

## Expected behavior
- DR14 and M139 are not referenced in any diagrams.
- DR14 and M139 are no longer in any exclusion
- Version 44 is not in production
=> I should be able to delete this drug and management

**Comment by alanvonlanthen** [comment]
nickel! Merci :)
