### ISSUE TITLE
Missing "fr" labels for answers in the SN algorithm (PH-#3293) #Urgent #TIMCI 

### ISSUE THREAD

**Issue by alanvonlanthen** [Wavemind/liwi-backend#126]
In https://medalcreator.unisante.ch/api/v1/versions/41, 
list of node IDs of the answers for which the mandatory "fr" label is missing: 
7553
7554
7555
7556
8307
8308
8366
8367
8191
8192
8187
8188
7802
7803
8149
8150
7414
7415
8159
8160
7227
7228
7861
7862
8368
8369
8370
8371
8375
8376
7698
7699
7800
7801
8358
8359
8345
8346
7938
7939
7936
7937
8377
8378
7859
7860
8224
8225
7731
7732
8082
8083
7847
7848
7580
7581
7376
7377

(Same list with their parent node if this helps: 
"Node : 9191 - Answer : 7553"
"Node : 9191 - Answer : 7554"
"Node : 9192 - Answer : 7555"
"Node : 9192 - Answer : 7556"
"Node : 9767 - Answer : 8307"
"Node : 9767 - Answer : 8308"
"Node : 9794 - Answer : 8366"
"Node : 9794 - Answer : 8367"
"Node : 9497 - Answer : 8191"
"Node : 9497 - Answer : 8192"
"Node : 9495 - Answer : 8187"
"Node : 9495 - Answer : 8188"
"Node : 9320 - Answer : 7802"
"Node : 9320 - Answer : 7803"
"Node : 9479 - Answer : 8149"
"Node : 9479 - Answer : 8150"
"Node : 9090 - Answer : 7414"
"Node : 9090 - Answer : 7415"
"Node : 9484 - Answer : 8159"
"Node : 9484 - Answer : 8160"
"Node : 8977 - Answer : 7227"
"Node : 8977 - Answer : 7228"
"Node : 9347 - Answer : 7861"
"Node : 9347 - Answer : 7862"
"Node : 9795 - Answer : 8368"
"Node : 9795 - Answer : 8369"
"Node : 9796 - Answer : 8370"
"Node : 9796 - Answer : 8371"
"Node : 9798 - Answer : 8375"
"Node : 9798 - Answer : 8376"
"Node : 9274 - Answer : 7698"
"Node : 9274 - Answer : 7699"
"Node : 9319 - Answer : 7800"
"Node : 9319 - Answer : 7801"
"Node : 9790 - Answer : 8358"
"Node : 9790 - Answer : 8359"
"Node : 9784 - Answer : 8345"
"Node : 9784 - Answer : 8346"
"Node : 9383 - Answer : 7938"
"Node : 9383 - Answer : 7939"
"Node : 9382 - Answer : 7936"
"Node : 9382 - Answer : 7937"
"Node : 9799 - Answer : 8377"
"Node : 9799 - Answer : 8378"
"Node : 9346 - Answer : 7859"
"Node : 9346 - Answer : 7860"
"Node : 9509 - Answer : 8224"
"Node : 9509 - Answer : 8225"
"Node : 9287 - Answer : 7731"
"Node : 9287 - Answer : 7732"
"Node : 9447 - Answer : 8082"
"Node : 9447 - Answer : 8083"
"Node : 9340 - Answer : 7847"
"Node : 9340 - Answer : 7848"
"Node : 9205 - Answer : 7580"
"Node : 9205 - Answer : 7581"
"Node : 9066 - Answer : 7376"
"Node : 9066 - Answer : 7377"
)

Resulting issue: JSON files produced by the tablets cannot be processed by medAL-data

**Comment by Devstrap** [comment]
@ManuBarchich After regeneration of the algo we are unable to update versions. In the endpoint IDs of the answers for which the mandatory "fr" label is always missing.

**Comment by Devstrap** [comment]
@frescoal We have regenerate the JSON of ePOCT+ TIMCI Senegal algorithm . Fix the missing "fr" labels for absent/present answers.But we still have an issue. We have a "en" key in the duration of management of the final diagnose but no "fr" key which is require because the default language of the server is French.

**Comment by Devstrap** [comment]
"final_diagnoses : 9840 - management : 9685"
"final_diagnoses : 9840 - management : 9753"
"final_diagnoses : 9840 - management : 9686"
"final_diagnoses : 9840 - management : 9694"
"final_diagnoses : 9840 - management : 9154"
"final_diagnoses : 9839 - management : 9682"
"final_diagnoses : 9839 - management : 9686"
"final_diagnoses : 9839 - management : 9753"
"final_diagnoses : 9836 - management : 9116"
"final_diagnoses : 9836 - management : 9115"
"final_diagnoses : 9836 - management : 9744"
"final_diagnoses : 10035 - management : 9230"
"final_diagnoses : 10035 - management : 9739"
"final_diagnoses : 10035 - management : 9765"
"final_diagnoses : 10035 - management : 9753"
"final_diagnoses : 10035 - management : 9685"
"final_diagnoses : 10159 - management : 9612"
"final_diagnoses : 10159 - management : 10158"
"final_diagnoses : 10159 - management : 9674"
"final_diagnoses : 9842 - management : 9686"
"final_diagnoses : 9842 - management : 9753"
"final_diagnoses : 9841 - management : 9753"
"final_diagnoses : 9841 - management : 9686"
"final_diagnoses : 9841 - management : 9694"
"final_diagnoses : 10013 - management : 9752"
"final_diagnoses : 10013 - management : 9753"
"final_diagnoses : 9889 - management : 9611"
"final_diagnoses : 9890 - management : 9809"
"final_diagnoses : 10019 - management : 9744"
"final_diagnoses : 10018 - management : 9690"
"final_diagnoses : 10018 - management : 9722"
"final_diagnoses : 9897 - management : 9725"
"final_diagnoses : 9897 - management : 9682"
"final_diagnoses : 9897 - management : 9653"
"final_diagnoses : 9898 - management : 9655"
"final_diagnoses : 9898 - management : 9680"
"final_diagnoses : 9898 - management : 9653"
"final_diagnoses : 9894 - management : 9753"
"final_diagnoses : 9894 - management : 9653"
"final_diagnoses : 9895 - management : 9682"
"final_diagnoses : 9895 - management : 9653"
"final_diagnoses : 9830 - management : 9116"
"final_diagnoses : 10014 - management : 9753"
"final_diagnoses : 10014 - management : 9735"
"final_diagnoses : 10015 - management : 9753"
"final_diagnoses : 10015 - management : 9752"
"final_diagnoses : 9853 - management : 9158"
"final_diagnoses : 9853 - management : 9173"
"final_diagnoses : 9853 - management : 9744"
"final_diagnoses : 9852 - management : 9744"
"final_diagnoses : 9852 - management : 8996"
"final_diagnoses : 9954 - management : 9753"
"final_diagnoses : 9954 - management : 9685"
"final_diagnoses : 10022 - management : 9744"
"final_diagnoses : 10020 - management : 9744"
"final_diagnoses : 9835 - management : 9116"
"final_diagnoses : 9833 - management : 9699"
"final_diagnoses : 9833 - management : 9753"
"final_diagnoses : 9844 - management : 9753"
"final_diagnoses : 9844 - management : 9694"
"final_diagnoses : 9844 - management : 9734"
"final_diagnoses : 9844 - management : 9691"
"final_diagnoses : 9844 - management : 9686"
"final_diagnoses : 9844 - management : 9685"
"final_diagnoses : 9843 - management : 9686"
"final_diagnoses : 9845 - management : 9753"
"final_diagnoses : 9845 - management : 9682"
"final_diagnoses : 9845 - management : 9685"
"final_diagnoses : 9845 - management : 9686"
"final_diagnoses : 9837 - management : 9699"
"final_diagnoses : 9837 - management : 9750"
"final_diagnoses : 9837 - management : 8979"
"final_diagnoses : 9837 - management : 9737"
"final_diagnoses : 23412 - management : 9764"
"final_diagnoses : 23412 - management : 9750"
"final_diagnoses : 23412 - management : 9699"
"final_diagnoses : 10029 - management : 9685"
"final_diagnoses : 10029 - management : 9808"
"final_diagnoses : 10028 - management : 9116"
"final_diagnoses : 10028 - management : 9115"
"final_diagnoses : 10032 - management : 9115"
"final_diagnoses : 9938 - management : 9160"
"final_diagnoses : 9938 - management : 9611"
"final_diagnoses : 9939 - management : 9611"
"final_diagnoses : 9939 - management : 10060"
"final_diagnoses : 9940 - management : 9809"
"final_diagnoses : 9940 - management : 9611"
"final_diagnoses : 9992 - management : 10088"
"final_diagnoses : 9992 - management : 10102"
"final_diagnoses : 9992 - management : 9612"
"final_diagnoses : 9988 - management : 10423"
"final_diagnoses : 9988 - management : 9612"
"final_diagnoses : 9988 - management : 9654"
"final_diagnoses : 9988 - management : 9742"
"final_diagnoses : 9989 - management : 9660"
"final_diagnoses : 9989 - management : 9659"
"final_diagnoses : 9870 - management : 9682"
"final_diagnoses : 10422 - management : 9612"
"final_diagnoses : 10422 - management : 10089"
"final_diagnoses : 10422 - management : 10088"
"final_diagnoses : 10422 - management : 10419"
"final_diagnoses : 10425 - management : 10426"
"final_diagnoses : 9926 - management : 9670"
"final_diagnoses : 9926 - management : 10058"
"final_diagnoses : 9926 - management : 9613"
"final_diagnoses : 9926 - management : 9611"
"final_diagnoses : 9926 - management : 10052"
"final_diagnoses : 9927 - management : 9670"
"final_diagnoses : 9927 - management : 9613"
"final_diagnoses : 9927 - management : 9611"
"final_diagnoses : 9928 - management : 9670"
"final_diagnoses : 9928 - management : 9612"
"final_diagnoses : 10064 - management : 9612"
"final_diagnoses : 10064 - management : 10070"
"final_diagnoses : 10065 - management : 10410"
"final_diagnoses : 10065 - management : 9611"
"final_diagnoses : 9945 - management : 9617"
"final_diagnoses : 9945 - management : 9611"
"final_diagnoses : 9946 - management : 9611"
"final_diagnoses : 9946 - management : 9617"
"final_diagnoses : 9951 - management : 9611"
"final_diagnoses : 9951 - management : 9627"
"final_diagnoses : 9951 - management : 9665"
"final_diagnoses : 9952 - management : 9665"
"final_diagnoses : 9952 - management : 9613"
"final_diagnoses : 9952 - management : 9611"
"final_diagnoses : 9942 - management : 9611"
"final_diagnoses : 9942 - management : 10062"
"final_diagnoses : 9943 - management : 9611"
"final_diagnoses : 9943 - management : 10036"
"final_diagnoses : 9941 - management : 9631"
"final_diagnoses : 9941 - management : 8998"
"final_diagnoses : 10033 - management : 9685"
"final_diagnoses : 10033 - management : 9765"
"final_diagnoses : 10033 - management : 9753"
"final_diagnoses : 9863 - management : 9612"
"final_diagnoses : 9863 - management : 9629"
"final_diagnoses : 9965 - management : 9611"
"final_diagnoses : 9965 - management : 9654"
"final_diagnoses : 9965 - management : 9680"
"final_diagnoses : 9965 - management : 9655"
"final_diagnoses : 9965 - management : 9653"
"final_diagnoses : 9964 - management : 9653"
"final_diagnoses : 9964 - management : 9612"
"final_diagnoses : 9920 - management : 9612"
"final_diagnoses : 9920 - management : 9624"
"final_diagnoses : 9921 - management : 9032"
"final_diagnoses : 9921 - management : 9624"
"final_diagnoses : 9921 - management : 9612"
"final_diagnoses : 10167 - management : 9611"
"final_diagnoses : 10167 - management : 9809"
"final_diagnoses : 10167 - management : 10052"
"final_diagnoses : 9877 - management : 9739"
"final_diagnoses : 9877 - management : 9614"
"final_diagnoses : 9877 - management : 9728"
"final_diagnoses : 9877 - management : 9611"
"final_diagnoses : 9877 - management : 9613"
"final_diagnoses : 10166 - management : 9611"
"final_diagnoses : 10166 - management : 9613"
"final_diagnoses : 10166 - management : 10052"
"final_diagnoses : 10008 - management : 9808"
"final_diagnoses : 10008 - management : 9231"
"final_diagnoses : 9993 - management : 9724"
"final_diagnoses : 9993 - management : 10419"
"final_diagnoses : 9993 - management : 9612"
"final_diagnoses : 9993 - management : 9725"
"final_diagnoses : 9987 - management : 9819"
"final_diagnoses : 9987 - management : 9612"
"final_diagnoses : 9987 - management : 9724"
"final_diagnoses : 9984 - management : 10416"
"final_diagnoses : 9984 - management : 9612"
"final_diagnoses : 9977 - management : 9654"
"final_diagnoses : 9977 - management : 10423"
"final_diagnoses : 9977 - management : 9612"
"final_diagnoses : 9977 - management : 9652"
"final_diagnoses : 9977 - management : 9657"
"final_diagnoses : 9996 - management : 9729"
"final_diagnoses : 9995 - management : 8979"
"final_diagnoses : 9982 - management : 9611"
"final_diagnoses : 9982 - management : 9668"
"final_diagnoses : 9956 - management : 9613"
"final_diagnoses : 9956 - management : 9714"
"final_diagnoses : 9955 - management : 9613"
"final_diagnoses : 9955 - management : 9612"
"final_diagnoses : 10030 - management : 9677"
"final_diagnoses : 10030 - management : 9733"
"final_diagnoses : 10030 - management : 9676"
"final_diagnoses : 10051 - management : 9724"
"final_diagnoses : 9925 - management : 9612"
"final_diagnoses : 9925 - management : 9724"
"final_diagnoses : 9913 - management : 9612"
"final_diagnoses : 9913 - management : 9641"
"final_diagnoses : 9913 - management : 9627"
"final_diagnoses : 9913 - management : 10088"
"final_diagnoses : 9913 - management : 10089"
"final_diagnoses : 9914 - management : 10090"
"final_diagnoses : 9919 - management : 9628"
"final_diagnoses : 9919 - management : 9611"
"final_diagnoses : 9919 - management : 10060"
"final_diagnoses : 9917 - management : 9629"
"final_diagnoses : 9917 - management : 9628"
"final_diagnoses : 9917 - management : 9611"
"final_diagnoses : 9918 - management : 9739"
"final_diagnoses : 9918 - management : 9611"
"final_diagnoses : 9918 - management : 10060"
"final_diagnoses : 9893 - management : 9611"
"final_diagnoses : 9893 - management : 9650"
"final_diagnoses : 9891 - management : 10088"
"final_diagnoses : 9891 - management : 10089"
"final_diagnoses : 9891 - management : 10102"
"final_diagnoses : 9874 - management : 9611"
"final_diagnoses : 9874 - management : 10074"
"final_diagnoses : 9873 - management : 9612"
"final_diagnoses : 9873 - management : 9713"
"final_diagnoses : 9909 - management : 10074"
"final_diagnoses : 9909 - management : 9611"
"final_diagnoses : 9909 - management : 9612"
"final_diagnoses : 9909 - management : 9613"
"final_diagnoses : 9859 - management : 9624"
"final_diagnoses : 9859 - management : 9612"
"final_diagnoses : 9859 - management : 9032"
"final_diagnoses : 9860 - management : 9611"
"final_diagnoses : 9860 - management : 9613"
"final_diagnoses : 9860 - management : 10052"
"final_diagnoses : 9959 - management : 9612"
"final_diagnoses : 9960 - management : 9611"
"final_diagnoses : 9892 - management : 9651"
"final_diagnoses : 9892 - management : 9611"
"final_diagnoses : 9892 - management : 10060"
"final_diagnoses : 9854 - management : 10132"
"final_diagnoses : 9854 - management : 9612"
"final_diagnoses : 9854 - management : 9032"
"final_diagnoses : 9856 - management : 9649"
"final_diagnoses : 9856 - management : 9644"
"final_diagnoses : 9856 - management : 9622"
"final_diagnoses : 9856 - management : 9645"
"final_diagnoses : 9879 - management : 9651"
"final_diagnoses : 9879 - management : 9611"
"final_diagnoses : 9880 - management : 9377"
"final_diagnoses : 9880 - management : 9759"
"final_diagnoses : 9880 - management : 9445"
"final_diagnoses : 9880 - management : 9612"
"final_diagnoses : 9880 - management : 10097"
"final_diagnoses : 9878 - management : 9718"
"final_diagnoses : 9886 - management : 9615"
"final_diagnoses : 9862 - management : 9809"
"final_diagnoses : 9862 - management : 10052"
"final_diagnoses : 9862 - management : 9613"
"final_diagnoses : 9896 - management : 10060"
"final_diagnoses : 9896 - management : 9649"
"final_diagnoses : 9896 - management : 9644"
"final_diagnoses : 9896 - management : 9645"
"final_diagnoses : 9896 - management : 9647"
"final_diagnoses : 9896 - management : 9622"
"final_diagnoses : 9861 - management : 10162"
"final_diagnoses : 9861 - management : 9724"
"final_diagnoses : 9861 - management : 9819"
"final_diagnoses : 9861 - management : 9032"
"final_diagnoses : 9924 - management : 9116"
"final_diagnoses : 9923 - management : 9116"
"final_diagnoses : 9923 - management : 9115"
"final_diagnoses : 9923 - management : 9682"
"final_diagnoses : 9933 - management : 9612"
"final_diagnoses : 9949 - management : 9612"
"final_diagnoses : 9857 - management : 9612"
"final_diagnoses : 9857 - management : 9624"
"final_diagnoses : 9857 - management : 9674"
"final_diagnoses : 9858 - management : 9611"
"final_diagnoses : 9858 - management : 9715"
"final_diagnoses : 9858 - management : 9687"
"final_diagnoses : 9858 - management : 9752"
"final_diagnoses : 11527 - management : 11528"
"final_diagnoses : 10042 - management : 9730"
"final_diagnoses : 10009 - management : 10144"
"final_diagnoses : 10009 - management : 10036"
"final_diagnoses : 10479 - management : 9647"
"final_diagnoses : 10479 - management : 9645"
"final_diagnoses : 10479 - management : 9649"
"final_diagnoses : 10479 - management : 9644"
"final_diagnoses : 9869 - management : 9611"
"final_diagnoses : 9875 - management : 9724"
"final_diagnoses : 9876 - management : 9133"
"final_diagnoses : 9876 - management : 9739"
"final_diagnoses : 9876 - management : 9611"
"final_diagnoses : 10017 - management : 9154"
"final_diagnoses : 10017 - management : 9173"
"final_diagnoses : 10016 - management : 9744"
"final_diagnoses : 10016 - management : 9724"
"final_diagnoses : 9867 - management : 9651"
"final_diagnoses : 9867 - management : 9611"
"final_diagnoses : 9867 - management : 9612"
"final_diagnoses : 10026 - management : 9808"
"final_diagnoses : 10027 - management : 9744"

**Comment by Devstrap** [comment]
Missing "fr" keys in final diagnoses for drugs _>
"final_diagnoses : 9840 - drugs : 9605"
"final_diagnoses : 9839 - drugs : 9603"
"final_diagnoses : 9897 - drugs : 9605"
"final_diagnoses : 9895 - drugs : 9605"
"final_diagnoses : 9843 - drugs : 9605"
"final_diagnoses : 9938 - drugs : 9559"
"final_diagnoses : 9938 - drugs : 9558"
"final_diagnoses : 9939 - drugs : 9543"
"final_diagnoses : 9941 - drugs : 9532"
"final_diagnoses : 9941 - drugs : 9396"
"final_diagnoses : 10030 - drugs : 23401"
"final_diagnoses : 10030 - drugs : 23402"
"final_diagnoses : 9919 - drugs : 9529"
"final_diagnoses : 9917 - drugs : 9589"
"final_diagnoses : 9917 - drugs : 9529"
"final_diagnoses : 9918 - drugs : 9529"
"final_diagnoses : 9874 - drugs : 9150"
"final_diagnoses : 9873 - drugs : 9396"
"final_diagnoses : 9909 - drugs : 9150"
"final_diagnoses : 9879 - drugs : 9609"
"final_diagnoses : 9880 - drugs : 9174"
