### ISSUE TITLE
Urgent | Links to original version persist in duplicated version (PH-#3690)

### ISSUE THREAD

**Issue by alanvonlanthen** [Wavemind/liwi-backend#150]
### Context:
* DYN RWANDA PROD https://medalcreator.unisante.ch/algorithms/6
* Original version: https://medalcreator.unisante.ch/algorithms/6/versions/39 
* Duplicates:
   ** https://medalcreator.unisante.ch/algorithms/6/versions/67 (couple of months old copy)
   ** https://medalcreator.unisante.ch/algorithms/6/versions/70 (2 week-old copy)

### Issue: 
When editing a treatment diagram from within a DD diagram of a duplicated version, you actually edit the treatment diagram of the original version (whether the version was created recently (70) or not (67)).

### Steps to replicate (with version 67): 
1. Open severe pneumonia DD diagram: https://medalcreator.unisante.ch/algorithms/6/versions/67/diagnoses/5450/diagram 
2. Open severe pneumonia DF diagram from within DD diagram: https://medalcreator.unisante.ch/algorithms/6/versions/67/diagnoses/5450/final_diagnoses/8494/diagram => you are actually editing the DF from version 70

### Additional information:
1. If edit DD and select DF via "Show" option arrive at correct (current) treatments diagram.  
2. Exports also affected e.g., if create Translations export get drug duration's from original version not from current.
3. Also happens with DYN TZ copy (version 69)

**Comment by alanvonlanthen** [comment]
20221004 - @GregMart1n no idea whether done or not. Needs to be re-tested. Pls check with Martin Norris for guidance

**Comment by GregMart1n** [comment]
This is dropped, assuming the refacto should fix that.
