### ISSUE TITLE
Drug qty and description not saved, or disapear... (PH #3700)

### ISSUE THREAD

**Issue by GregMart1n** [Wavemind/liwi-backend#155]
## Describe the bug
The quantity and description of a drug seem to be not saved properly or disapear in a very random way...
This is happening when editing a diagram (shown in attached video).

## Context
- Environment medAL-creator (test, prod) for Senegal
- Tried with drug DR19 as it was reported by a user.

## To Reproduce
There is no clear way on how to reproduce...
I was lucky in the video because it appeared right away. This is how I spotted the problem by the way, I was investingating a different behavior. Sometimes it takes me 5-6 times or more to reproduce it.

## Expected behavior
Values saved.

## Screenshots
Video attached

https://user-images.githubusercontent.com/109588388/181025999-e9414111-9926-4740-843a-0b368e36daae.mp4

**Comment by GregMart1n** [comment]
Hi, just coming back on this issue, as it is critical on our side. 
This may not give the needed information on the drugs to administer to the children. Which becomes a health problem.

Many thanks

**Comment by GregMart1n** [comment]
Reached out to Manu via Slack as we need this issue to be solved rapidly.

**Comment by GregMart1n** [comment]
I have been able to reproduce de problem. It seems that something happen when the drug is moved on the diagram. If you just add the drug et leave it there, the data stay. If I move it, data are gone after reloading.

https://user-images.githubusercontent.com/109588388/186107055-1b58d975-6055-434d-ab57-cda03b9f34b2.mp4

**Comment by GregMart1n** [comment]
Seems to not have the problem on an other algo whith another variable.

**Comment by alanvonlanthen** [comment]
20221004 - Can probably wait to see if refacto fixes the issue
