### ISSUE TITLE
"Full consulation order" page won't show. (HP#3710)

### ISSUE THREAD

**Issue by GregMart1n** [Wavemind/liwi-backend#157]
## Describe the bug
when going on https://medalcreator.unisante.ch/algorithms/6/versions/40, it is not possible to display information on the tab [ Full consultation order ].

ePOCT+ Dynamic Rwanda - version ePOCT+_DYN_RW_Control_Arm_v0.1_PROD

## Context
- https://medalcreator.unisante.ch/algorithms/6/versions/40
- Tried on different computers with different accounts.

## To Reproduce
1. go on https://medalcreator.unisante.ch/algorithms/6/versions/40
2. click on Full consultation order
3. ❌ nothing happens

## Expected behavior
For the information to be displayed

## Additional information
right click > open in a new tab = HTTP ERROR 406

The original request I received :
Symptômes  :

1. sur medAL-data, Sylvain reçoit un tableau tronqué. Il a un **null** à la place de la dernière valeur dans les enfants du système "Eye / visual system" (c'est comme ça qu'on a vu le problème)
2. dans medAL-creator en prod, je n'arrive pas à ouvrir la vue "Full consultation order" pour cette version (tu cliques et il ne se passe rien).

**Comment by GregMart1n** [comment]
UPDATE ⚠️ : This is happening for all RW algorithms

**Comment by alanvonlanthen** [comment]
/!\ Also happening for TIMCI TZ: https://medalcreator.unisante.ch/algorithms/5/versions/34 
ping @ManuBarchich

**Comment by GregMart1n** [comment]
@ManuBarchich Have you done anything ?
Seems to work fine now.
