### ISSUE TITLE
Arrow disappear when editing cut-offs values

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-backend#17]
## Describe the bug
Arrow disappear following scenario below

## To Reproduce
1. Go to a QS
2. Drag and put "Default true" on the diagram
3. Connect "Default true" to another box with an arrow
4. Right click on the arrow to set values in Months
5. Press save
6. Right click again on the arrow to modify values (when modifying a value arrow disappear)
7. Press save 
8. See error

## Expected behavior
Arrow shouldn't disappear when editing cut-offs values

## Desktop
 - Browser: Microsoft Edge

**Comment by ManuBarchich** [comment]
Je n'arrive pas à reproduire le bug en suivant les points ci-dessus

**Comment by jouz56k** [comment]
On peut s'appeler si tu veux, et je t'explique comment faire, car je ne vois pas comment expliquer autrement (Je viens de reproduire selon le scenario exposé)
