### ISSUE TITLE
In the refacto version -> Villages shouldn't be mandatory

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-backend#18]
## Describe the request
In the refacto version -> Villages shouldn't be mandatory
-> We don't want to deal anymore with villages in TIMCI algos

## Screenshots
See error when deleting Villages from TIMCI
![image](https://user-images.githubusercontent.com/55558015/125770411-3240bcf0-55ff-49ac-ac6f-a6e0722a24a3.png)

**Comment by ManuBarchich** [comment]
La question du village est une Basic Question set en dur dans l'algo, comment voulez-vous procéder pour indiquer si oui ou non on l'utilise ?

**Comment by jouz56k** [comment]
@ManuBarchich déso pas vu ta question, je voulais vérifier cette issue sur les villages, mais je ne connais pas le contexte, j'ai écrit le commentaire ci-haut selon Alan, mais je n'ai pas saivi ou est-ce que les villages ne doivent pas être mandatory?
