### ISSUE TITLE
Color for YI questions in "Full consultation order" is not appropriate

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-backend#19]
## Describe the request
Use this pink as the background color for the box, and use a black font

## Screenshots
![fdgfdg](https://user-images.githubusercontent.com/55558015/125801958-aab023c7-25d9-47d6-8085-b5a9a3006eb8.PNG)

**Comment by frescoal** [comment]
Is it worth to fix this as we are goin

**Comment by frescoal** [comment]
Is it worth to fix as a full UX/UI refactor is planned ?

**Comment by jouz56k** [comment]
If quickly fix (less than one hour) -> Lets go
If not, we can wait

**Comment by jouz56k** [comment]
We wait Ingrid project to be implemented
