### ISSUE TITLE
Cut-offs view extension (medal-c)

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-backend#22]
**medAL-creator**

Currently there is a view in Diagnoses diagrams that allow us to see the range of age values (cut-offs)
-> See picture

Request 1: Extend this view to all the related Treatment diagrams 

Request 2: Replace "From" by "From ≥" and "to" by "to <" in order to make it clear what is inclusive or not (can be critical for YI)

**Screenshot**
![fsdfsd](https://user-images.githubusercontent.com/55558015/126455194-b7bc5ed5-9187-4fc9-9fbc-e323b35381e9.PNG)

**Comment by frescoal** [comment]
The whole design will change is it worth to change it?

**Comment by jouz56k** [comment]
It can help clin-it team when dealing with cut-offs (to avoid confusions) during this refacto period
-> Is it too much time to implement that @frescoal

**Comment by ManuBarchich** [comment]
Fait et déployé

**Comment by jouz56k** [comment]
@ManuBarchich Magnifique
