### ISSUE TITLE
Quickfix : remove "test/assessment is unavailable" option from Appetite test

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-backend#26]
## Describe the request
As now we have the tickbox having this option in the dropdown menu has become redundant
![fghhfg](https://user-images.githubusercontent.com/55558015/126992134-423903e7-6a77-42f4-84df-4c8dab2303fb.PNG)

**Comment by ManuBarchich** [comment]
Quel environment ?
Quel id de question ?

**Comment by jouz56k** [comment]
J'attends la réponse des médecins et te redis

**Comment by ManuBarchich** [comment]
Fermer cette issue vue qu'elle est redondante avec la #31 ?

**Comment by jouz56k** [comment]
Oui
