### ISSUE TITLE
Issues with Villages

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-backend#27]
## Describe the bug
1. Impossible to upload a Village file in medAL-c (Villages section) for FEVER TRAVEL
-> See screenshot 1 to observe error
2. Impossible to Add Fever Travel Version 1.0 to HF José Paz (158)
-> See screenshot 2 to observe error

## Context
- Environment : https://liwi-test.wavelab.top/
- To observe error 1 : https://liwi-test.wavelab.top/algorithms/10?panel=versions
- To observe error 2 : https://liwi-test.wavelab.top/health_facilities/158

## Expected behavior
1. Should be able to upload a Village
2. Should be able to generate json with and without a Village file imported

## Screenshots
1.
![fdgfdgdfg](https://user-images.githubusercontent.com/55558015/127136166-bd137676-091f-4101-959f-9024cfac87d1.PNG)
2.
![fdgfdgfdg](https://user-images.githubusercontent.com/55558015/127136148-f3ff540b-34c3-43fa-b0f6-7ef1acb33c06.PNG)

## Desktop
 - Browser : Microsoft Edge

**Comment by ManuBarchich** [comment]
1. Fixed, la solution sera déployée d'ici 10 minutes.
2. L'erreur est normale puisque la question Village est instanciée dans la version. Il faut l'enlever de la version si on ne souhaite pas l'utiliser.
