### ISSUE TITLE
Remove "Assessment is unavailable" from the dropdown of "Appetite test" 

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-backend#31]
## Describe the request
As medical team can use tickbox "unavailable", they want to remove "Assessment is unavailable" from the dropdown of "Appetite test" in all studies.

**Here is the list:**

Dyn TZ : 3487, A75, Appetite test
https://liwi-test.wavelab.top/algorithms/1/questions/3487/edit

Dyn RW : 8084, A75, Appetite test
https://liwi-test.wavelab.top/algorithms/6/questions/8084/edit

TIMCI Kenya : 11171, A17, Appetite test
https://liwi-test.wavelab.top/algorithms/8/questions/11171/edit

TIMCI Senegal : 9491, A17, Appetite test
https://liwi-test.wavelab.top/algorithms/7/questions/9491/edit

TIMCI TZ : 5808, A17, Appetite test
https://liwi-test.wavelab.top/algorithms/5/questions/5808/edit

**Comment by ManuBarchich** [comment]
La réponse qu'on me demande de supprimée est utilisée dans les DD145 Malnutrition, j'aimerais une confirmation sur ce DD avant si possible svp
