### ISSUE TITLE
Task: please export a list of users that have been doing changes to variables or diagrams between the 22.09 and now (PH-#2643)

### ISSUE THREAD

**Issue by alanvonlanthen** [Wavemind/liwi-backend#66]

**Comment by ManuBarchich** [comment]
["Emmanuel Barchichat", "Peter Agrea", "Serge Zimulinda", "Gillian Levine", "Sabine  Rengli", "Valsini Mbongo", "Oswald Luoga", "Martin Norris 2", "Sasha Kulinkina", "Issa Laye Marone Diop", "Rainer Tan", "Anmol Jacob", "Alwi Haji", "Lisa Cleveley", "Alan Vonlanthen", "Alain Fresco", "Vincent Faivre", "Alan Vonlanthen", "MedAl-CRW Generic User Rw", "Fenella Beynon", "Ludovico Cobuccio", "MedAl-C TIMCI Generic user", "Quentin Girard", "MedAl-C Generic user", "TIMCI TZ Generic user", "TIMCI SN Generic User"]
