### ISSUE TITLE
Task: reorder answers in drop-down lists for Dynamic Rwanda (PH-#2635)

### ISSUE THREAD

**Issue by alanvonlanthen** [Wavemind/liwi-backend#67]
Please re-order the following variable dropdown lists:

**What kind of consultation is this?** (7531 / D35)
- New consultation
- Follow-up (unscheduled)
- Follow-up (scheduled)
- Referral from another facility
- Referral from CHW

**Caregiver relationship** (7976/D30)
- Mother/father
- Aunt/Uncle
- Grandparent
- Sister/Brother
- Neighbor/Friend
- Other
**_- DELETE cousin_**

**Owner of primary phone** (7607/D12)
- Primary caregiver
- Person inside household
- Person outside household
- CHW
- No phone number
 
**Owner of second phone** (7609/D13)
- Primary caregiver
- Person inside household
- Person outside household
- CHW

**Comment by ManuBarchich** [comment]
@quentingirard Il faudrait ordrer les listes déroulantes en fonction de la référence
